name: Backport trigger

on:
  issue_comment:
    types: [created]

jobs:
  backport:
    if: ${{ github.event.issue.pull_request }}
    uses: oat-sa/backport-action/.github/workflows/backport-on-comment.yml@v1

    # Required permissions for the called workflow
    permissions:
      contents: write
      pull-requests: write

    # Pass repository secrets through
    secrets: inherit